- Raven.Abstractions/Connection/WebResponseExtensions.cs
- Raven.Abstractions/Extensions/TaskExtensions.cs
- Raven.Client.Lightweight/Connection/AdminRequestCreator.cs
- Raven.Client.Lightweight/Connection/Async/AsyncAdminServerClient.cs
- Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
- Raven.Client.Lightweight/Connection/Async/AsyncServerClientBase.cs
- Raven.Client.Lightweight/Connection/Async/IAsyncDatabaseCommands.cs
- Raven.Client.Lightweight/Connection/IReplicationInformerBase.cs
- Raven.Client.Lightweight/Connection/ReplicationInformerBase.cs
- Raven.Client.Lightweight/Connection/ServerClient.cs
- Raven.Client.Lightweight/Document/DocumentStore.cs
- Raven.Client.Lightweight/Indexes/AbstractIndexCreationTask.cs
- Raven.Client.Lightweight/Indexes/AbstractResultsTransformer.cs
- Raven.Tests.Core/ChangesApi/ImplementingChangesClient.cs
- Raven.Tests.Core/Commands/Documents.cs
- Raven.Tests.Issues/RavenDB_752.cs
- Raven.Tests.Issues/ReplicationBehavior.cs
* added extension method for cancelling tasks with await keyword -> WithCancellation(CancellationToken)
* Added optional cancellation token to interface implementations of async client api
> RavenDB-3025 fix

- Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
- Raven.Client.Lightweight/Connection/IRavenQueryInspector.cs
- Raven.Client.Lightweight/Document/AbstractDocumentQuery.cs
- Raven.Client.Lightweight/Document/Async/AsyncDocumentSession.cs
- Raven.Client.Lightweight/Document/AsyncDocumentQuery.cs
- Raven.Client.Lightweight/Document/Batches/ILazySessionOperations.cs
- Raven.Client.Lightweight/Document/InMemoryDocumentSessionOperations.cs
- Raven.Client.Lightweight/IAsyncAdvancedSessionOperations.cs
- Raven.Client.Lightweight/IAsyncDocumentQuery.cs
- Raven.Client.Lightweight/IAsyncDocumentSession.cs
- Raven.Client.Lightweight/IAsyncDocumentSessionImpl.cs
- Raven.Client.Lightweight/Linq/IRavenQueryProvider.cs
- Raven.Client.Lightweight/Linq/RavenQueryInspector.cs
- Raven.Client.Lightweight/Linq/RavenQueryProvider.cs
- Raven.Client.Lightweight/PublicExtensions/LinqExtensions.cs
- Raven.Client.Lightweight/Shard/AsyncShardedDocumentSession.cs
- Raven.Client.Lightweight/Shard/BaseShardedDocumentSession.cs
- Raven.Client.Lightweight/Shard/ShardedRavenQueryInspector.cs
- Raven.Tests/Bugs/IteratingTwice.cs
added async cancelation support to Linq extensions and session implementations.
> RavenDB-3025

- Raven.Database/Indexing/Index.cs
- Raven.Database/Storage/BaseRestoreOperation.cs
Remove the exception thrown from index backup.
In stand if an exception is thrown a file is written to the backup folder indicating the index backup was faulty.
on the restore operation we detect indexes that failed to store and reset them.
> Failure to backup index shouldn't fail the whole backup

- Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
- Raven.Client.Lightweight/DocumentStoreBase.cs
- Raven.Client.Lightweight/Indexes/AbstractIndexCreationTask.cs
- Raven.Client.Lightweight/Indexes/IndexCreation.cs
- Raven.Client.Lightweight/Shard/ShardedDocumentStore.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3071.cs
for details see http://issues.hibernatingrhinos.com/issue/RavenDB-3071
> Added support for CreateIndexesAsync in sharded environment

- Raven.Client.Lightweight/Document/Async/AsyncDocumentSession.cs
- Raven.Client.Lightweight/Document/DocumentSession.cs
- Raven.Client.Lightweight/DocumentStoreBase.cs
- Raven.Client.Lightweight/Indexes/IndexCreation.cs
- Raven.Client.Lightweight/Linq/IDocumentQueryGenerator.cs
- Raven.Client.Lightweight/Linq/RavenQueryInspector.cs
- Raven.Client.Lightweight/Linq/RavenQueryProvider.cs
- Raven.Client.Lightweight/Shard/AsyncShardedDocumentSession.cs
- Raven.Client.Lightweight/Shard/BaseShardedDocumentSession.cs
- Raven.Client.Lightweight/Shard/ShardedDocumentSession.cs
- Raven.Client.Lightweight/Shard/ShardedDocumentStore.cs
- Raven.Client.Lightweight/Shard/ShardedRavenQueryInspector.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3096.cs
this commit includes fixes for:
http://issues.hibernatingrhinos.com/issue/RavenDB-3096
and
http://issues.hibernatingrhinos.com/issue/RavenDB-3071
> Facet and Index creation on sharded document store fix

- Raven.Voron/Voron/Impl/Paging/AbstractPager.cs
- Raven.Voron/Voron/Trees/Tree.MultiTree.cs
> RavenDB-3101

- Raven.Client.Lightweight/Document/Async/AsyncDocumentSession.cs
- Raven.Client.Lightweight/Document/DocumentSession.cs
- Raven.Client.Lightweight/Linq/IDocumentQueryGenerator.cs
- Raven.Client.Lightweight/Linq/RavenQueryInspector.cs
- Raven.Client.Lightweight/Linq/RavenQueryProvider.cs
- Raven.Client.Lightweight/Shard/AsyncShardedDocumentSession.cs
- Raven.Client.Lightweight/Shard/BaseShardedDocumentSession.cs
- Raven.Client.Lightweight/Shard/ShardStrategy.cs
- Raven.Client.Lightweight/Shard/ShardedDocumentSession.cs
- Raven.Client.Lightweight/Shard/ShardedRavenQueryInspector.cs
- Raven.Tests/Bugs/Facets/RavenDB_3096.cs
- Raven.Tests/Bugs/ShardedIdGenerationTest.cs
- Raven.Tests/Raven.Tests.csproj
http://issues.hibernatingrhinos.com/issue/RavenDB-3096
I have added the test from 3.0 and passed it as well as all the facet and query tests in 2.5.
I'm not sure that i have gone through all the execution paths though since i dont know if the flag SILVERLIGHT is on or not in the test context.
> facet on sharded session don't work

- Raven.Abstractions/Extensions/StreamExtensions.cs
* replace Marshal.SizeOf with sizeof()
* reading from stream with a loop
> RavenDB-3121 fix

- Raven.Abstractions/Data/Constants.cs
- Raven.Database/Config/InMemoryRavenConfiguration.cs
- Raven.Database/Config/StronglyTypedRavenSettings.cs
- Raven.Database/Server/HttpServer.cs
- RavenDB.sln.DotSettings
- default.ps1
http://issues.hibernatingrhinos.com/issue/RavenDB-3141
> added the option to configure timeouts/threads while database is been loaded

- Raven.Abstractions/Data/Constants.cs
- Raven.Database/Config/InMemoryRavenConfiguration.cs
- Raven.Database/Config/StronglyTypedRavenSettings.cs
- Raven.Database/Server/AppBuilderExtensions.cs
- Raven.Database/Server/Controllers/RavenBaseApiController.cs
- Raven.Database/Server/Controllers/RavenDbApiController.cs
see http://issues.hibernatingrhinos.com/issue/RavenDB-3144
> Added support to configure the timeout of a task waiting for a database to be loaded

- Raven.Database/Data/CommandDataFactory.cs
- Raven.Tests.FileSystem/ClientApi/FileSessionTests.cs
Passing tests for parallel download using commands interface.
> Fixed: foundCharacter variable does not exists & Passing tests.

- Raven.Database/Storage/BaseBackupOperation.cs
1. we should backup data before indexes to avoid situations where statistics are newer than backup-ed indexes
2. if this is incremental backup, we should ensure that directory exists
> fixing backup

- Raven.Database/Bundles/ScriptedIndexResults/ScriptedIndexResultsJsonPatcherScope.cs
- Raven.Database/Json/ScriptedJsonPatcher.cs
- Raven.Database/Json/ScriptedJsonPatcherOperationScope.cs
for each LoadDocument in script, increase total available steps in the script (relative for size of loaded document)o
> RavenDB-3215

- Raven.Client.Lightweight/Indexes/AbstractIndexCreationTask.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3277.cs
Added Auto sort for fields with numerical values
> RavenDB-3277 Automatic sorting for AbstractIndexCreationTask

- Raven.Client.Lightweight/Connection/SerializationHelper.cs
- Raven.Client.Lightweight/RavenQueryStatistics.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3300.cs
> RavenDB-3300 Expose ResultEtag to RavenQueryStatistics

- Raven.Database/Server/Controllers/BulkInsertController.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_1041.cs
- Raven.Tests.Issues/RavenDB_3230.cs
This issue is related to triggers not been able to access thread local information like the User.
for more details see http://issues.hibernatingrhinos.com/issue/RavenDB-3230
> Fixed an issue where using bulk insert won't copy thread local information

- Raven.Database/Json/ScriptedJsonPatcher.cs
- Raven.Studio.Html5/App/models/dto.ts
- Raven.Studio.Html5/App/models/versioningEntry.ts
- Raven.Studio.Html5/App/viewmodels/globalConfigVersioning.ts
- Raven.Studio.Html5/App/views/versioning.html
- Raven.Studio.Html5/Raven.Studio.Html5.csproj
applied missing commits + after merge fixes
> after merge fixes

- Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
- Raven.Client.Lightweight/Connection/IDatabaseCommands.cs
- Raven.Client.Lightweight/Connection/ServerClient.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3285.cs
Setting index lock on client side
> RavenDB-3285 Add a way to set index lock mode from the client API

- Raven.Studio.Html5/App/viewmodels/replications.ts
- Raven.Studio.Html5/Raven.Studio.Html5.csproj
* updated Typescript version to 1.4
* fixing error that worked for earlier version of Typescript
> update of Typescript version and fixing the resulting compilation error

- Raven.Client.Lightweight/Document/AbstractDocumentQuery.cs
fixing NRE in tests -> wrong commit description string
> RavenDB-3334 fix

- Raven.Studio.Html5/App/models/filesystem/fileMetadata.ts
minor change, fixing TS compilation error after update to 1.4
> RavenDB-3330

- Raven.Abstractions/Data/Constants.cs
- Raven.Abstractions/Data/UuidType.cs
- Raven.Database/Actions/NotificationActions.cs
- Raven.Database/Actions/TransformerActions.cs
- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Database/Server/Controllers/IndexController.cs
- Raven.Database/Server/Controllers/TransformersController.cs
- Raven.Database/Storage/IndexDefinitionStorage.cs
- Raven.Database/Util/SequentialUuidGenerator.cs
- Raven.Tests.Core/Replication/TransformerReplication.cs
* better way to handle already deleted transformers & indexes
* added transformer deletion replication
> changes related to RavenDB-3304

- Raven.Database/Actions/DocumentActions.cs
- Raven.Database/Actions/QueryActions.cs
- Raven.Database/DocumentDatabase.cs
- Raven.Database/Server/Controllers/StreamsController.cs
- Raven.Database/Server/Controllers/StudioTasksController.cs
- Raven.Database/Server/Tenancy/DatabaseLandlord.cs
- Raven.Database/Server/WebApi/RequestManager.cs
simply update last used time in database during long operations
> RavenDB-3269

- Raven.Abstractions/Data/Constants.cs
- Raven.Database/Config/InMemoryRavenConfiguration.cs
- Raven.Database/Config/StronglyTypedRavenSettings.cs
- Raven.Database/Json/ScriptedJsonPatcher.cs
- Raven.Tests.Core/ScriptedPatching/ScriptedPatchTests.cs
add to scripted patching/index function to increase number of available steps from inside the script itself --> IncreaseNumberOfAllowedStepsBy(int number)
> RavenDB-3216 fix

- Raven.Abstractions/Raven.Abstractions.csproj
- Raven.Abstractions/Util/Encryptors/DefaultEncryptor.cs
- Raven.Abstractions/Util/Encryptors/HashEncryptorBase.cs
- Raven.Abstractions/Util/MD5.cs
- Raven.Abstractions/Util/ObjectPool.cs
- Raven.Database/Actions/IndexActions.cs
- Performance improvements on MD5Core of 5x.
> Crypto algorithms optimizations.

- Raven.Voron/Voron/Impl/WriteBatch.cs
Size() is now calculated when transactions are added and/or removed. Gains of 30% when handling Outstanding Transactions.
> Write Batch Improvements

- Raven.Client.Lightweight/Document/GenerateEntityIdOnTheClient.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3422.cs
fixing issue with generating Id for a document with Int Id property and default value
> RavenDB-3422

- Raven.Abstractions/Data/CompactStatus.cs
- Raven.Database/FileSystem/Controllers/AdminFileSystemController.cs
- Raven.Database/Server/Controllers/Admin/AdminController.cs
- Raven.Studio.Html5/App/commands/filesystem/startCompactCommand.ts
- Raven.Studio.Html5/App/commands/startCompactCommand.ts
- Raven.Studio.Html5/App/models/dto.ts
- Raven.Studio.Html5/App/viewmodels/compact.ts
- Raven.Studio.Html5/App/views/compact.html
http://issues.hibernatingrhinos.com/issue/RavenDB-3418
I have removed reports of compaction progress, now we only hold the latest.
We still issue the rest of the messages but they are not the issue.
> Performance issues when compacting a large database

- Raven.Tests.Issues/RavenDB-3152.cs
Export Incremental is working fine, it's using the same code - ExportDocument which was fixed
> RavenDB-3152 Smuggler client side filtering should not impact how we get the next etag

- Raven.Studio.Html5/App/commands/filesystem/getFileCommand.ts
- Raven.Studio.Html5/App/models/filesystem/file.ts
- Raven.Studio.Html5/App/viewmodels/filesystem/fileRenameDialog.ts
- Raven.Studio.Html5/App/viewmodels/filesystem/filesystemFiles.ts
- Raven.Studio.Html5/App/views/filesystem/filesystemFiles.html
added renaming selected file, changed the file id to observable
Signed-off-by: Hila Mefano <hila@ayende.com>
> RavenDB-3391 Files view, should be able to rename a file when selected

- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3393.cs
can't reproduce
Signed-off-by: Hila Mefano <hila@ayende.com>
> RavenDB-3393 DatabaseCommands.ForDatabase(...) in embedded in-memory database returns commands for system database

- Raven.Database/Storage/Voron/StorageActions/IndexingStorageActions.cs
- Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs
17% improvement on DeleteMappedResult.
> RavenDB-3461

- Raven.Client.Lightweight/Document/Async/AsyncDocumentSession.cs
- Raven.Client.Lightweight/Document/InMemoryDocumentSessionOperations.cs
- Raven.Client.Lightweight/IAsyncAdvancedSessionOperations.cs
- Raven.Client.Lightweight/Shard/AsyncShardedDocumentSession.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3451.cs
Added GetMetadataForAsync
Didn't implement GetMetadataForAsync for sharded documentStore
Signed-off-by: Hila Mefano <hila@ayende.com>
> RavenDB-3451 Provide GetMetadataForAsync for async session

- Raven.Abstractions/MEF/OrderedPartCollection.cs
- Raven.Database/Bundles/Replication/Responders/Behaviors/SingleItemReplicationBehavior.cs
- Raven.Tests.Common/ReplicationBase.cs
- Raven.Tests/Issues/RavenDB_3435.cs
- Raven.Tests/Raven.Tests.csproj
>  RavenDB-3435 fix (ported from 3.0)

- Raven.Client.Lightweight/Document/IAsyncLoaderWithInclude.cs
RavenDB-3474 Include with TInclude on async
> Hillel raven db 3474

- Raven.Database/Server/Controllers/StudioTasksController.cs
- Raven.Database/Smuggler/SmugglerEmbeddedDatabaseOperations.cs
- Raven.Studio.Html5/App/viewmodels/filesystem/importFilesystem.ts
- Raven.Studio.Html5/App/viewmodels/filesystem/tasks.ts
- Raven.Studio.Html5/App/viewmodels/importDatabase.ts
- Raven.Studio.Html5/App/views/exportDatabase.html
- Raven.Studio.Html5/App/views/filesystem/exportFilesystem.html
- Raven.Studio.Html5/App/views/filesystem/importFilesystem.html
- Raven.Studio.Html5/App/views/importDatabase.html
- import database advanced settings typo
- tooltip javascript code fix
> RavenDB-3498 Strip replication information isn't working when importing

- Raven.Abstractions/Data/Constants.cs
- Raven.Database/Config/InMemoryRavenConfiguration.cs
- Raven.Database/Config/StronglyTypedRavenSettings.cs
- Raven.Database/Server/RavenDbServer.cs
- Raven.Database/Server/WebApi/Filters/RavenExceptionFilterAttribute.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3501.cs
adding MaxClauseCount config setting -> change maximum query clause count
> RavenDB-3501 fix

- Raven.Client.Lightweight/IAsyncDocumentSession.cs
http://english.stackexchange.com/a/88403
> fix comment

- Raven.Client.Lightweight/Indexes/AbstractScriptedIndexCreationTask.cs
- Raven.Client.Lightweight/Indexes/IndexCreation.cs
- Raven.Client.Lightweight/Raven.Client.Lightweight.csproj
- Raven.Tests.Bundles/Raven.Tests.Bundles.csproj
- Raven.Tests.Bundles/ScriptedIndexResults/Animal_Stats_Scripts.cs
- Raven.Tests.Bundles/ScriptedIndexResults/ScriptedIndexResultsTest.cs
I wrote this for an internal project. Polished it a little bit for general usage.
> Scripted index creation task

- Raven.Studio.Html5/App/models/dto.ts
- Raven.Studio.Html5/App/models/environmentColor.ts
- Raven.Studio.Html5/App/viewmodels/shell.ts
- Raven.Studio.Html5/App/viewmodels/studioConfig.ts
RavenDB-3481 removed unused parameter from environmentColor
> Hillel raven db 3481

- Raven.Voron/Voron.Tests/FixedSize/SimpleFixedSizeTrees.cs
- Raven.Voron/Voron/Trees/Fixed/FixedSizeTree.cs
- Raven.Voron/Voron/Trees/Fixed/Iterators.cs
Conflicts:
Raven.Voron/Voron.Tests/FixedSize/SimpleFixedSizeTrees.cs
Raven.Voron/Voron/Trees/Fixed/FixedSizeTree.cs
Raven.Voron/Voron/Trees/Fixed/Iterators.cs
> FixedSizeTree should be more inlined with the regular tree's API

- Raven.Abstractions/Connection/HttpRavenRequest.cs
Now replication feature works (still a phase in the test doesn't, but with studio creating 2 dbs with replication works and they update each other with new/modified documents.
> Set ContentLength of WebRequest in mono BEFORE GetRequestStream

- Raven.Database/Server/AppBuilderExtensions.cs
Skip "Write failure" Exceprion in Mono (and any other exception in any platform) - fix string
> Skip "Write failure" Exceprion

- Raven.Studio.Html5/App/common/aceEditorBindingHandler.ts
- Raven.Studio.Html5/App/viewmodels/patch.ts
- Raven.Studio.Html5/App/viewmodels/query.ts
RavenDB-3515 Query intellisense/autocomplete is unreliable in Studio
fixed inconsistent behavior in query, patch, and indexes
> Hillel raven db 3515

- Bundles/Raven.Bundles.LiveTest/LiveTestResourceCleanerStartupTask.cs
- Raven.Database/Plugins/Builtins/CheckFreeDiskSpace.cs
- Raven.Database/Plugins/Builtins/CheckIncrementalBackupStatus.cs
- Raven.Database/Plugins/IServerStartupTask.cs
- Raven.Database/Server/RavenDBOptions.cs
- Raven.Database/Server/RavenDbServer.cs
- Raven.Tests.Bundles/LiveTest/StartupTaskTests.cs
- changed IServerStartupTask interface
from
void Execute(RavenDbServer server);
to
void Execute(RavenDBOptions serverOptions);
> fixed an issue with IServerStartupTask's not starting when hosted on IIS

- Raven.Abstractions/Extensions/TaskExtensions.cs
- Raven.Abstractions/Raven.Abstractions.csproj
- Raven.Abstractions/Replication/SideBySideReplicationInfo.cs
- Raven.Database/Bundles/Replication/Controllers/ReplicationController.cs
- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3573.cs
side-by-side index replication
(backported from v3.0)
> RavenDB-3573 fix (side-by-side index replication, backported from 3.0)

- Raven.Database/DiskIO/DiskPerformanceTester.cs
- Raven.Database/Server/Controllers/Admin/AdminController.cs
make sure unhandled exceptions during disk i/o test won't crash the raven process
> RavenDB-3645 fix

- Raven.Tests.Issues/RavenDB_3629.cs
- Raven.Tryouts/Program.cs
fixed race condition in a unit test
> RavenDB-3629 fix

- Raven.Studio.Html5/App/viewmodels/editDocument.ts
- Raven.Studio.Html5/App/views/editDocument.html
at document edit screen: make related document link appear with "..." if too long
> RavenDB-3650 fix

- Raven.Client.Lightweight/Document/AbstractDocumentQuery.cs
- Raven.Client.Lightweight/Document/SortOptionsEqualityProvider.cs
- Raven.Client.Lightweight/Raven.Client.Lightweight.csproj
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3543.cs
make sure that sort hints do not contain multiple entries for the same field (while building the query)
> RavenDB-3675 fix

- Raven.Database/Actions/QueryActions.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-3683
> Added the time it took to parse the query to the query time.

- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
do not replicate index & transformer deletion if in the meantime it has been recreated
> RavenDB-3686 fix (index deletion replication)

- Raven.Abstractions/Indexing/TransformerDefinition.cs
- Raven.Abstractions/Indexing/TransformerLockMode.cs
- Raven.Abstractions/Raven.Abstractions.csproj
- Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
- Raven.Client.Lightweight/Connection/Async/IAsyncDatabaseCommands.cs
- Raven.Client.Lightweight/Connection/IDatabaseCommands.cs
- Raven.Client.Lightweight/Connection/ServerClient.cs
- Raven.Database/Actions/TransformerActions.cs
- Raven.Database/Server/Controllers/TransformersController.cs
- Raven.Database/Storage/IndexDefinitionStorage.cs
- Raven.Studio.Html5/App/commands/saveTransformerLockModeCommand.ts
- Raven.Studio.Html5/App/models/dto.ts
- Raven.Studio.Html5/App/models/transformer.ts
- Raven.Studio.Html5/App/viewmodels/indexesAndTransformersClipboardDialog.ts
- Raven.Studio.Html5/App/viewmodels/transformers.ts
- Raven.Studio.Html5/App/views/transformers.html
- Raven.Studio.Html5/Raven.Studio.Html5.csproj
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3647.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-3647
> Adding Transformer LockMode

- Raven.Tests.Issues/RavenDB_3570.cs
make the issue fixing test skip because otherwise it breaks the build
> RavenDB-3570 related adjustment

- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/packages.config
- Raven.Tests/Replication/IndexReplication.cs
use index multi-put for index replication
> RavenDB-3677 fix

- Raven.Client.Lightweight/Shard/ShardedRavenQueryInspector.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3609.cs
https://github.com/ayende/ravendb/compare/ayende:v3.5...hilaMef:RavenDB-3609?expand=1
> RavenDB-3609 Querying asynchronously a sharded dataset with facet

- Raven.Database/Indexing/LuceneAST.cs
- Raven.Database/Server/Controllers/RavenBaseApiController.cs
- Raven.Tests.Issues/RavenDB_3460.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-3708
The problem was that In method node was not overriding the field name,
so the wrong anlyzer was invoked.
> Raven db 3708

- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3726.cs
https://github.com/ayende/ravendb/compare/ayende:v3.5...hilaMef:RavenDB-3726?expand=1
> RavenDB-3726

- Raven.Studio.Html5/App/viewmodels/database/patch/patch.ts
This looks like a merge gone wrong but i might be missing something here.
It seems i did nothing that should affect the functionality of the code but it somehow did fix the problem.
> Patched document not showing in the studio

- Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
- Raven.Client.Lightweight/Connection/ServerClient.cs
- Raven.Client.Lightweight/Indexes/AbstractIndexCreationTask.cs
- Raven.Tests.Common/ReplicationBase.cs
- Raven.Tests/Replication/IndexReplication.cs
use proper sync/async primitive (AsyncHelpers)
> RavenDB-3743 fix

- Raven.Database/Counters/Controllers/AdminCounterStorageController.cs
- Raven.Database/Counters/Controllers/CounterOperationsController.cs
- Raven.Tests.Counters/CountersChangeTests.cs
- Raven.Tests.Counters/RavenBaseCountersTest.cs
Fixing a test - making it pass
> some minor stuff

- Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs
- Raven.Client.Lightweight/Indexes/AbstractIndexCreationTask.cs
- Raven.Database/Actions/IndexActions.cs
- Raven.Studio.Html5/App/views/indexes.html
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3758.cs
Fix SideBySide index overwrite
> Run only one precomputed indexing batch

- Raven.Client.Lightweight/Linq/RavenQueryInspector.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-3763.cs
https://github.com/ayende/ravendb/compare/v3.5...hilaMef:RavenDB-3763-fixed?expand=1
> RavenDB-3763 In using Async session

- Raven.Studio.Html5/App/commands/getIndexingStatusCommand.ts
- Raven.Studio.Html5/App/common/recentQueriesStorage.ts
- Raven.Studio.Html5/App/viewmodels/query.ts
- Raven.Studio.Html5/App/viewmodels/resources.ts
- Raven.Studio.Html5/App/viewmodels/shell.ts
- Raven.Studio.Html5/App/viewmodels/toggleIndexing.ts
- Raven.Studio.Html5/App/viewmodels/viewModelBase.ts
- Raven.Studio.Html5/App/views/toggleIndexing.html
RavenDB-3789 Disable/Enable indexing
> RavenDB-3520 Cannot query dynamic index using the studio - the studio seems to not function

- Raven.Abstractions/Counters/CounterStorageDocument.cs
- Raven.Abstractions/Counters/CounterSummary.cs
- Raven.Abstractions/Smuggler/SmugglerMode.cs
- Raven.Client.Lightweight/Counters/CounterStore.Admin.cs
- Raven.Client.Lightweight/Counters/CounterStore.cs
- Raven.Client.Lightweight/Extensions/MultiDatabase.cs
- Raven.Database/Counters/Backup/BackupOperation.cs
- Raven.Database/Counters/Controllers/AdminCounterStorageController.cs
- Raven.Database/Counters/CounterStorage.cs
- Raven.Database/Raven.Database.csproj
- Raven.Database/Server/Controllers/DebugController.cs
- Raven.Database/Server/Tenancy/CountersLandlord.cs
- Raven.Database/Smuggler/SmugglerCounterApi.cs
- Raven.Database/Smuggler/SmugglerCounterOperationDispatcher.cs
- Raven.Database/Smuggler/SmugglerOperationDispatcher.cs
- Raven.Server/FromMono/Options.cs
- Raven.Smuggler/Program.cs
- Raven.Tests.Counters/BackupRestoreTests.cs
- Raven.Tests.Counters/CountersBasicClientTests.cs
- Raven.Tests.Counters/Raven.Tests.Counters.csproj
- Raven.Tests.Counters/SmugglerTests.cs
- Raven.Tryouts/Program.cs
Also contains some minor fixes and refactorings
> RavenDB-3643 related changes - Counter Smuggler API integration with Raven.Smuggler

- Raven.Studio.Html5/App/models/dto.ts
- Raven.Studio.Html5/App/viewmodels/database/status/statistics.ts
- Raven.Studio.Html5/App/views/database/status/statistics.html
https://github.com/ayende/ravendb/compare/ayende:v3.5...hilaMef:RavenDB-3804?expand=1
> Raven db 3804

- Raven.Database/Counters/Controllers/AdminCounterStorageController.cs
- Raven.Tests.Counters/CounterAuthTests.cs
- Raven.Tests.Counters/RavenBaseCountersTest.cs
- Raven.Tests.Counters/SmugglerTests.cs
* minor refactoring for counters admin controller
* more unit tests for counters auth
> RavenDB-3643 related changes - auth tests and some refactorings

- Raven.Studio.Html5/App/viewmodels/database/indexes/copyIndexDialog.ts
https://github.com/ayende/ravendb/compare/v3.5...hilaMef:RavenDB-3693?expand=1
> RavenDB-3693 Paste of an index definition when it exist will fail because the index exist

- Rachis/Rachis.Tests/HttpTransportPingTest.cs
- Rachis/Rachis.Tests/Rachis.Tests.csproj
- Rachis/Rachis/RaftEngine.cs
- default.ps1
- zzz_RavenDB_Release.sln
Leader_removed_from_cluster_modifies_member_lists_on_remaining_nodes(nodeCount:2) randomly fails, especially during the command line build process
> Rachis tests fixes

- Raven.Monitor/CPU/CpuPerformanceMonitoring.cs
- Raven.Monitor/CPU/CpuUssageReportDoc.cs
- Raven.Monitor/IMonitor.cs
- Raven.Monitor/IO/Data/DiskQueueReportDoc.cs
- Raven.Monitor/IO/DiskIoPerformanceMonitor.cs
- Raven.Monitor/IO/DiskQueuePerformanceMonitor.cs
- Raven.Monitor/Memory/MemoryPerformanceMonitor.cs
- Raven.Monitor/Memory/MemoryUssageReportDoc.cs
- Raven.Monitor/MonitorActions.cs
- Raven.Monitor/MonitorController.cs
- Raven.Monitor/MonitorHost.cs
- Raven.Monitor/MonitorOptions.cs
- Raven.Monitor/MonitoringManager.cs
- Raven.Monitor/Program.cs
- Raven.Monitor/Raven.Monitor.csproj
- Raven.Monitor/RavenDocumentStore.cs
- Raven.Monitor/packages.config
This commit has the changes i have made to run the monitoring tool as a server.
> Raven.Monitor run as server

- Rachis/Rachis.Tests/Rachis.Tests.csproj
- Rachis/Rachis.Tests/packages.config
- Raven.SlowTests/app.config
- Raven.Sparrow/Sparrow.Tests/Sparrow.Tests.csproj
- Raven.Tests.Core/Raven.Tests.Core.csproj
- Raven.Tests.Core/packages.config
- Raven.Tests.Counters/Raven.Tests.Counters.csproj
- Raven.Tests.Counters/packages.config
- Raven.Tests.FileSystem/Raven.Tests.FileSystem.csproj
- Raven.Tests.FileSystem/packages.config
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3570.cs
- Raven.Tests.Issues/app.config
- Raven.Tests.Issues/packages.config
- Raven.Tests.MailingList/Raven.Tests.MailingList.csproj
- Raven.Tests.MailingList/packages.config
- Raven.Tests.Raft/Raven.Tests.Raft.csproj
- Raven.Tests.TimeSeries/Raven.Tests.TimeSeries.csproj
- Raven.Tests.TimeSeries/packages.config
- Raven.Tests/Raven.Tests.csproj
- Raven.Tests/packages.config
- Raven.Tryouts/app.config
I had to update the fluent assertion version from 3.5 to 4.0
it seems i also updated the web api in a few projects i think that can be ignored.
> Fixing Fluent assertions reference issue

- Raven.Client.Lightweight/Indexes/IndexCreation.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3864.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-3864
> Raven db 3864

- Raven.Database/Bundles/SqlReplication/SqlReplicationTask.cs
> Fixing sql replication retry timing

- Raven.Database/Smuggler/SmugglerFilesApi.cs
It got broken due to the controller refactoring need to verify with Pawel that my changes are correct.
> Fixing ShouldThrowIfFileSystemDoesNotExist

- Raven.Client.Lightweight/Indexes/ExpressionStringBuilder.cs
- Raven.Client.Lightweight/Linq/LinqPathProvider.cs
Can you please review the changes i have made to LinqPathProvider.GetValueFromExpressionWithoutConversion
> Fixing issues with empty array in linq 

- Raven.Abstractions/Data/ChangeNotification.cs
- Raven.Abstractions/Indexing/IndexDefinition.cs
- Raven.Database/Actions/IndexActions.cs
- Raven.Database/Bundles/Replication/Tasks/IndexReplicationTask.cs
- Raven.Database/Storage/IndexDefinitionStorage.cs
- Raven.Tests.Raft/Client/Indexes.cs
- Raven.Tests/Replication/TransformerReplication.cs
- Raven.Tryouts/Raven.Tryouts.csproj
Please review the changes i have made for indexing before i apply the same changes to transformers.
> Index version to fix index replication problem (Read comment inside)

- Raven.Database/Bundles/Replication/Tasks/IndexReplicationTask.cs
- Raven.Database/FileSystem/Controllers/ConfigController.cs
- Raven.Tests.Common/Util/ProxyServer.cs
- Raven.Tests.FileSystem/CommandsUsage.cs
I don't want to send them in one huge PR
> A few test fixes (from Raven db 3939 )

- Raven.Database/Bundles/Replication/Tasks/IndexReplicationTask.cs
- Raven.Database/Storage/IndexDefinitionStorage.cs
now also preventing old index version to be put into the database if an older version of the index is been deleted.
> Added some comments to index version and some log messages

- Raven.Abstractions.Database/Json/JintOperationScope.cs
- Raven.Database/Actions/IndexActions.cs
- Raven.Database/Bundles/ScriptedIndexResults/ScriptedIndexResultsIndexTrigger.cs
- Raven.Database/Indexing/IndexingExecuter.cs
- Raven.Database/Indexing/MapReduceIndex.cs
- Raven.Database/Indexing/SimpleIndex.cs
- Raven.Database/Prefetching/PrefetchingBehavior.cs
- Raven.Tests.Common/Attributes/FactIfSqlServerIsAvailable.cs
- Raven.Tests.Issues/Prefetcher/RavenDB_3581.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_3985.cs
- Raven.Tests.Issues/RavenDB_3994.cs
- Raven.Tests.Issues/RavenDB_3996.cs
- Raven.Tests.Issues/RavenDB_XXXX.cs
- cleanup.ps1
Only the ones made by @arekais and @ppekrol + 1 by @ayende
> applied 3.0 fixes to 4.0

- Raven.Database/Commercial/ValidateLicense.cs
- Raven.Database/Rhino.Licensing/AbstractLicenseValidator.cs
- Raven.Database/Rhino.Licensing/Discovery/DiscoveryHost.cs
- Raven.Database/Rhino.Licensing/LicenseValidator.cs
- Raven.Database/Rhino.Licensing/StringLicenseValidator.cs
This is a fix for Pluralsight problem of leaking UDP connection in 2.5 ported fix from 3.0
> Fix for RavenDB-4013

- Raven.Abstractions/Data/Constants.cs
- Raven.Database/Config/InMemoryRavenConfiguration.cs
- Raven.Database/Config/StronglyTypedRavenSettings.cs
- Raven.Database/Server/HttpServer.cs
- Raven.Tryouts/Program.cs
adding semaphore to database loading -> prevent from loading too much at the same time
> RavenDB-4022 fix

- Raven.Abstractions/Data/Constants.cs
- Raven.Database/Config/InMemoryRavenConfiguration.cs
- Raven.Database/Config/StronglyTypedRavenSettings.cs
- Raven.Database/Server/Tenancy/AbstractLandlord.cs
- Raven.Database/Server/Tenancy/CountersLandlord.cs
- Raven.Database/Server/Tenancy/DatabaseLandlord.cs
- Raven.Database/Server/Tenancy/FileSystemsLandlord.cs
make config key and variable names agnostic of resource type
> RavenDB-4030 related minor refactoring

- Raven.Abstractions/Data/Constants.cs
- Raven.Abstractions/Exceptions/ConcurrentLoadTimeoutException.cs
- Raven.Abstractions/Raven.Abstractions.csproj
- Raven.Database/Common/ResourceApiController.cs
- Raven.Database/Config/Categories/ServerConfiguration.cs
- Raven.Database/Config/Retriever/ConfigurationSettingsDocument.cs
- Raven.Database/Server/Tenancy/AbstractLandlord.cs
- Raven.Database/Server/Tenancy/CountersLandlord.cs
- Raven.Database/Server/Tenancy/DatabaseLandlord.cs
- Raven.Database/Server/Tenancy/FileSystemsLandlord.cs
- Raven.Database/Server/Tenancy/TimeSeriesLandlord.cs
make sure that only configured number of resources get loaded at the same time
> RavenDB-4030 fix

- Raven.Database/Bundles/SqlReplication/SqlReplicationTask.cs
- Raven.Database/Extensions/RoleFinder.cs
- Raven.Database/Indexing/IndexingExecuter.cs
- Raven.Database/Prefetching/ConcurrentJsonDocumentSortedList.cs
- Raven.Database/Prefetching/Prefetcher.cs
- Raven.Database/Prefetching/PrefetchingBehavior.cs
- Raven.Database/Server/Controllers/RavenDbApiController.cs
- Raven.Database/Server/Controllers/StudioTasksController.cs
- Raven.Database/Server/Tenancy/AbstractLandlord.cs
- Raven.Tests/Bugs/BulkInsert.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-3898
http://issues.hibernatingrhinos.com/issue/RavenDB-4031
> RavenDB-3898 & RavenDB-4031

- Raven.Client.Lightweight/FileSystem/AsyncFilesServerClient.cs
- Raven.Database/Bundles/Versioning/Triggers/VersioningPutTrigger.cs
- Raven.Database/FileSystem/Bundles/Versioning/Plugins/VersioningTriggerActions.cs
- Raven.Database/FileSystem/Bundles/Versioning/VersioningUtil.cs
- Raven.Database/FileSystem/Controllers/FsStudioTasksController.cs
- Raven.Database/Server/Controllers/BulkInsertController.cs
- Raven.Smuggler/Program.cs
- Raven.Studio.Html5/App/commands/filesystem/importFilesystemCommand.ts
- Raven.Studio.Html5/App/viewmodels/filesystem/tasks/importFilesystem.ts
- Raven.Studio.Html5/App/views/filesystem/tasks/importFilesystem.html
- Raven.Tests.Bundles/Versioning/Versioning.cs
- Raven.Tests.FileSystem/Bundles/Versioning/VersioningTests.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
https://github.com/ayende/ravendb/compare/v3.5...hilaMef:RavenDB_3979new?expand=1
> RaveDB-3979

- Raven.Studio.Html5/App/models/database/query/querySort.ts
- Raven.Studio.Html5/App/viewmodels/database/query/query.ts
https://github.com/ayende/ravendb/compare/v3.5...hilaMef:RavenDB-4018?expand=1
> RavenDB-4018

- Rachis/Rachis.Tests/DictionaryStateMachine.cs
- Rachis/Rachis/Behaviors/LeaderStateBehavior.cs
Also removing AutoResetEvent from Heartbeat.
>  DictionaryStateMachine last index stalness

- Rachis/Rachis.Tests/DictionaryStateMachine.cs
- Rachis/Rachis/Behaviors/LeaderStateBehavior.cs
Also removing the Heartbeat AutoResetEvent
> DictionaryStateMachine index staleness fix

- Raven.Studio.Html5/App/views/database/settings/replications.html
- Raven.Studio.Html5/App/views/manage/globalConfig/globalConfigReplications.html
http://issues.hibernatingrhinos.com/issue/RavenDB-3935
> RavenDB-3935: [v4.0] Remove leftovers which caused the issue

- Raven.Database/Rhino.Licensing/SntpClient.cs
The underlining problem was not closing the Sntp socket when successfully getting the Date from the server.
> Fix for RavenDB-4083

- Raven.Abstractions/Connection/HttpRavenRequestFactory.cs
- Raven.Abstractions/Data/ConnectionStringParser.cs
- Raven.Abstractions/FileSystem/SynchronizationDestination.cs
- Raven.Abstractions/FileSystem/SynchronizationException.cs
- Raven.Abstractions/Replication/ReplicationDestination.cs
- Raven.Client.Lightweight/Connection/Async/AsyncServerClientBase.cs
- Raven.Client.Lightweight/FileSystem/Extensions/FilesSynchronizationExtensions.cs
- Raven.Client.Lightweight/FileSystem/FilesStore.cs
- Raven.Client.Lightweight/FileSystem/SynchronizationServerClient.cs
- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Database/FileSystem/Synchronization/SynchronizationTask.cs
- Raven.Tests.Bundles/Encryption/EncryptionBackupAndRestore.cs
- Raven.Tests.Common/ReplicationBase.cs
- Raven.Tests.FileSystem/Auth/ClientWindowsAuth.cs
- Raven.Tests.FileSystem/Auth/ClientWindowsAuth2.cs
- Raven.Tests.FileSystem/Auth/SynchronizationWithWindowsAuth.cs
- Raven.Tests.FileSystem/Raven.Tests.FileSystem.csproj
- Raven.Tests.Helpers/RavenFilesTestBase.cs
- Raven.Tests/Security/ReplicationWithMixedSecurity.cs
@ayende Please do not merge this yet, I would want to see test results on your setup first.
> RDBQA-45 fixed all windows authentication tests

- Raven.Abstractions/Data/ChangeNotification.cs
- Raven.Database/Actions/AttachmentActions.cs
- Raven.Database/Actions/NotificationActions.cs
- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Database/Indexing/WorkContext.cs
- Raven.Tests.Raft/RaftTestBase.cs
moved replication task to wait on database notification rather than work context DoWork
> RavenDB-4094 + RavenDB-4095:

- Raven.Database/Raft/ClusterManager.cs
- Raven.Tests.Raft/RaftTestBase.cs
- Raven.Tests.Raft/RaftWithAuth.cs
Forcing election on cluster creation in RaftTestBase
> RavenDB-4124:

- Raven.Client.Lightweight/Connection/RavenUrlExtensions.cs
Removed redundant string allocation from RavenUrlExtensions.cs
> RavenDB-3971:

- Raven.Tests.Web/Controllers/Commands/AsyncCommandsController.cs
- Raven.Tests.Web/Controllers/Commands/MixedCommandsController.cs
- Raven.Tests.Web/Controllers/Commands/SyncCommandsController.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4127
> RavenDB-4127 Fix failing tests

- Rachis/Rachis/Transport/HttpTransportSender.cs
Fix for Raven.Tests.Raft.Client.WithFailovers
> RavenDB-4125

- Raven.Studio.Html5/App/views/versioning.html
https://github.com/ayende/ravendb/compare/master...hilaMef:RavenDB-4081-v3.0?expand=1
> RavenDB-4081

- Raven.Voron/Voron/Data/RawData/RawDataSection.cs
- Raven.Voron/Voron/Data/Tables/Table.cs
Missing return on Delete Section code.
Improperly handling the indexing where moving data on section relocation.
> Fixes from code review

- Raven.Database/Json/JintOperationScope.cs
- Raven.Tests.Issues/RavenDB-4144.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4144
> RavenDB-4144 Patch crashes the server

- Raven.Abstractions.Database/Json/JintOperationScope.cs
- Raven.Tests.Issues/RavenDB-4144.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4144
> RavenDB-4144 Patch crashes the server-4.0

- Raven.Database/Indexing/AbstractIndexingExecuter.cs
- Raven.Database/Indexing/ReducingExecuter.cs
- Raven.Database/Storage/IMappedResultsStorageAction.cs
- Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs
- Raven.Studio.Html5/App/models/dto.ts
- Raven.Studio.Html5/App/views/counter/counters.html
- Raven.Studio.Html5/App/views/database/documents/deleteCollection.html
- Raven.Studio.Html5/App/views/database/documents/documents.html
- Raven.Studio.Html5/App/views/database/documents/editDocument.html
- Raven.Studio.Html5/App/views/database/query/queryStatsDialog.html
- Raven.Studio.Html5/App/views/filesystem/files/filesystemFiles.html
- Raven.Tests/Storage/Voron/MappedResultsStorageActionsTests.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4141
> RavenDB-4141-4.0 Remove obsolete scheduled reductions

- Raven.Database/Indexing/AbstractIndexingExecuter.cs
- Raven.Database/Indexing/ReducingExecuter.cs
- Raven.Database/Storage/Esent/StorageActions/MappedResults.cs
- Raven.Database/Storage/IMappedResultsStorageAction.cs
- Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs
- Raven.Studio.Html5/App/models/dto.ts
- Raven.Studio.Html5/App/views/deleteCollection.html
- Raven.Studio.Html5/App/views/documents.html
- Raven.Studio.Html5/App/views/editDocument.html
- Raven.Studio.Html5/App/views/filesystem/filesystemFiles.html
- Raven.Studio.Html5/App/views/queryStatsDialog.html
- Raven.Tests/Storage/Voron/MappedResultsStorageActionsTests.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4141
> RavenDB-4141 Remove obsolete scheduled reductions

- Raven.Abstractions.Database/Json/JintOperationScope.cs
- Raven.Tests.Issues/RavenDB_3197.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4144
> RavenDB-4144-4.0 Patch crashes the server

- Raven.Client.Lightweight/Connection/DocumentConventionJsonExtensions.cs
- Raven.Database/Indexing/MapReduceIndex.cs
- Raven.Database/Storage/Esent/StorageActions/MappedResults.cs
- Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-4153.cs
- Raven.Tests.Issues/RavenDB_784.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4153
> RavenDB-4153 reduce_key_types isn't clear after deleting all documents

- Raven.Client.Lightweight/Connection/DocumentConventionJsonExtensions.cs
- Raven.Database/Indexing/MapReduceIndex.cs
- Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-4153.cs
- Raven.Tests.Issues/RavenDB_784.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4153
> RavenDB-4153 4.0 reduce_key_types isn't clear after deleting all document

- Raven.Database/Server/Tenancy/DatabaseLandlord.cs
- Raven.Database/Server/Tenancy/FileSystemsLandlord.cs
- Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs
- Raven.Tests/Storage/Bugs/GetReduceKeysAndTypesNotPagingProperly.cs
- Raven.Tests/Storage/Voron/MappedResultsStorageActionsTests.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4169
http://issues.hibernatingrhinos.com/issue/RavenDB-4170
http://issues.hibernatingrhinos.com/issue/RavenDB-4171
> RavenDB-4169 & RavenDB-4170 & RavenDB-4171 [3.0]

- Raven.Database/Server/Tenancy/CountersLandlord.cs
- Raven.Database/Server/Tenancy/DatabaseLandlord.cs
- Raven.Database/Server/Tenancy/FileSystemsLandlord.cs
- Raven.Database/Server/Tenancy/TimeSeriesLandlord.cs
- Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs
- Raven.Tests/Storage/Bugs/GetReduceKeysAndTypesNotPagingProperly.cs
- Raven.Tests/Storage/Voron/MappedResultsStorageActionsTests.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4169
http://issues.hibernatingrhinos.com/issue/RavenDB-4170
http://issues.hibernatingrhinos.com/issue/RavenDB-4171
> RavenDB-4169 & RavenDB-4170 & RavenDB-4171 [4.0]

- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
* removing unused hasMoreWork
* adding missing cancellation token
> RavenDB-4146 minor changes

- Raven.Studio.Html5/App/common/changesApi.ts
- Raven.Studio.Html5/App/models/filesystem/synchronizationDestination.ts
- Raven.Studio.Html5/App/models/replicationDestination.ts
- Raven.Studio.Html5/App/viewmodels/filesystem/synchronizationDestinations.ts
- Raven.Studio.Html5/App/viewmodels/resources.ts
- Raven.Studio.Html5/App/viewmodels/shell.ts
- Raven.Studio.Html5/App/views/filesystem/synchronizationDestinations.html
http://issues.hibernatingrhinos.com/issue/RavenDB-4197
> RavenDB-4197 Replication URL should be set to current server by default

- Imports/Newtonsoft.Json/Src/Newtonsoft.Json/JsonTextReader.cs
- Raven.Abstractions/Smuggler/SmugglerApiBase.cs
- Raven.Tests/Issues/LargeAttachmentsImportShouldWork.cs
- Raven.Tryouts/Program.cs
fixing ReadBytesAsStream() exiting the loop too early
> RavenDB-4194 fix

- Raven.Database/Config/InMemoryRavenConfiguration.cs
- Raven.Database/Config/StronglyTypedRavenSettings.cs
- Raven.Database/Impl/NullDocumentCacher.cs
- Raven.Database/Raven.Database.csproj
- Raven.Database/Storage/Esent/TransactionalStorage.cs
- Raven.Database/Storage/Voron/TransactionalStorage.cs
I changed it from 'Raven/UseNullDocumentCacher' to 'Raven/CacheDocumentsInMemory'
> RavenDB-4116 - Add option to disable document caching

- Raven.Client.Lightweight/Document/RemoteBulkInsertOperation.cs
- Raven.Database/Server/Responders/BulkInsert.cs
- Raven.Tests/Issues/LargeAttachmentsImportShouldWork.cs
- Raven.Tryouts/Program.cs
* make sure that bulk insert operation in smuggler import does not time out if attachments are large 
* relevant tests
> RavenDB-4196 fix

- Raven.Client.Lightweight/Document/AbstractDocumentQuery.cs
- Raven.Client.Lightweight/Document/IAbstractDocumentQuery.cs
- Raven.Client.Lightweight/Linq/IRavenQueryable.cs
- Raven.Client.Lightweight/Linq/RavenQueryInspector.cs
- Raven.Client.Lightweight/Linq/RavenQueryProvider.cs
- Raven.Client.Lightweight/Linq/RavenQueryProviderProcessor.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_4231.cs
Query with transformer should respect the original query type
http://issues.hibernatingrhinos.com/issue/RavenDB-4231
> RavenDB-4231 Please review, this is sensitive code.

- Raven.Database/DiskIO/DiskPerformanceTester.cs
- Raven.Database/Embedded/ResponseStream.cs
Not properly disposing CancellationTokenSources after linking them
> RavenDB-4231

- Raven.Database/Commercial/ValidateLicense.cs
- Raven.Database/Rhino.Licensing/AbstractLicenseValidator.cs
OEM/ISV License Validations should not impact startup performance
> RavenDB-4243

- src/Sparrow/Platform/Posix/PosixUnmanagedMemory.cs
- src/Sparrow/Platform/UnmanagedMemory.cs
- src/Sparrow/Platform/Win32/Win32UnmanagedMemory.cs
- src/Sparrow/project.json
- src/Voron/Platform/Posix/AllowBuildOnWindows.cs
- src/Voron/Platform/Posix/PosixHelper.cs
- src/Voron/Platform/Posix/PosixJournalWriter.cs
- src/Voron/Platform/Posix/PosixMemoryMapPager.cs
- src/Voron/Platform/Posix/PosixTempMemoryMapPager.cs
- src/Voron/StorageEnvironmentOptions.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4119
> V4.0dnx fin

- Raven.Client.Lightweight/Indexes/ExpressionStringBuilder.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB_4053.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4053
> RavenDB-4053

- Raven.Database/Storage/Voron/StorageActions/DocumentsStorageActions.cs
- Raven.Tests.MailingList/PeterBalzli.cs
- Raven.Tests.MailingList/Raven.Tests.MailingList.csproj
http://issues.hibernatingrhinos.com/issue/RavenDB-4251
> RavenDB-4251 Index gets never unstale

- Raven.Database/Storage/Voron/StorageActions/DocumentsStorageActions.cs
- Raven.Tests.MailingList/PeterBalzli.cs
- Raven.Tests.MailingList/Raven.Tests.MailingList.csproj
http://issues.hibernatingrhinos.com/issue/RavenDB-4251
> RavenDB-4251-4.0 Index gets never unstale

- Raven.Database/Rhino.Licensing/SntpClient.cs
> RavenDB-4252

- Raven.Database/Rhino.Licensing/SntpClient.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4252
> RavenDB-4252 (UDP Port leak)

- src/Raven.Server/Utils/WelcomeMessage.cs
> V4.0 dnx server on linux

- Imports/Newtonsoft.Json/Src/Newtonsoft.Json/JsonTextReader.cs
- Raven.Abstractions/Json/JsonTextReader.cs
- Raven.Abstractions/Raven.Abstractions.csproj
- Raven.Abstractions/Smuggler/SmugglerDatabaseApiBase.cs
- Raven.Tests.Core/project.json
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-4196.cs
- Raven.Tryouts/project.json
> RavenDB-4196 fix -> port to 3.0

- Rachis/Rachis/Behaviors/AbstractRaftStateBehavior.cs
- Rachis/Rachis/Behaviors/CandidateStateBehavior.cs
- Rachis/Rachis/Behaviors/LeaderStateBehavior.cs
- Rachis/Rachis/Rachis.csproj
- Rachis/Rachis/RaftEngine.cs
- Rachis/Rachis/RaftEngineStatistics.cs
- Raven.Abstractions/Extensions/ConcurrentQueueExtensions.cs
- Raven.Abstractions/Raven.Abstractions.csproj
- Raven.Database/Server/Controllers/Admin/AdminController.cs
- Raven.Tests.Raft/RaftTestBase.cs
Raft Statistics 
http://issues.hibernatingrhinos.com/issue/RavenDB-4162
> RavenDB-4162

- Raven.Database/Impl/DocumentRetriever.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/ThorMigrationIssues.cs
> properly respect AllowMultipleIndexEntriesForSameDocumentToResultTransformer flag for queries with transformers

- Bundles/Raven.Bundles.UniqueConstraints/UniqueConstraintsPutTrigger.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4282
> RavenDB-4282 ( UniqueConstraintsPutTrigger)

- Raven.Client.Lightweight/Indexes/ExpressionStringBuilder.cs
- Raven.Client.Lightweight/Indexes/IndexDefinitionHelper.cs
- Raven.Tests/MailingList/BadTransformerDef.cs
- Raven.Tests/Raven.Tests.csproj
porting a 3.0 fix for bad transformer definition in vs2015
(about the issue mentioned here https://groups.google.com/forum/#!msg/ravendb/Qf4g1FVmi58/Mj7eeeZ0AgAJ)
> port of 2015 transformer definition fix (that was done for 3.0)

- Rachis/Rachis/Behaviors/AbstractRaftStateBehavior.cs
- Rachis/Rachis/Behaviors/CandidateStateBehavior.cs
- Rachis/Rachis/Behaviors/LeaderStateBehavior.cs
- Rachis/Rachis/Rachis.csproj
- Rachis/Rachis/RaftEngine.cs
- Rachis/Rachis/RaftEngineStatistics.cs
- Raven.Abstractions/Extensions/ConcurrentQueueExtensions.cs
- Raven.Abstractions/Raven.Abstractions.csproj
- Raven.Database/Server/Controllers/Admin/AdminController.cs
- Raven.Tests.Raft/RaftTestBase.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4162
> RavenDB-4162_v4 (Raft Statistics)

- Bundles/Raven.Bundles.UniqueConstraints/UniqueConstraintsPutTrigger.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4282
> RavenDB-4282 (UniqueConstraintsPutTrigger)

- src/Raven.Server/Documents/BulkInsertHandler.cs
- src/Raven.Server/Documents/DocumentsHandler.cs
- src/Raven.Server/Json/BlittableJsonDocumentBuilder.cs
- src/Raven.Server/Json/BlittableJsonReaderBase.cs
- src/Raven.Server/Json/BlittableJsonReaderObject.cs
- src/Raven.Server/Json/BlittableJsonTextWriter.cs
- src/Raven.Server/Json/Parsing/IJsonParser.cs
- src/Raven.Server/Json/Parsing/ObjectJsonParser.cs
- src/Raven.Server/Json/Parsing/UnmanagedJsonParserAbstract.cs
- src/Raven.Server/Json/Parsing/UnmanagedJsonParserBase.cs
- src/Raven.Server/Json/Parsing/UnmanagedJsonStreamParser.cs
- src/Raven.Server/Json/Parsing/UnmanagedJsonWebSocketParser.cs
- src/Raven.Server/Json/RavenOperationContext.cs
- src/Raven.Server/Json/UnmanagedWriteBuffer.cs
- src/Raven.Server/Program.cs
- src/Raven.Server/Routing/Trie.cs
- src/Raven.Server/Web/System/AdminDatabases.cs
- src/Raven.Server/Web/System/BuildVersion.cs
- src/Raven.Server/project.json
- test/BlittableTests/Benchmark/ProfilerWork.cs
- test/BlittableTests/Benchmark/WriteToStreamBenchmark.cs
- test/BlittableTests/BlittableJsonWriterTests/BlittableFormatTests.cs
- test/BlittableTests/BlittableJsonWriterTests/ConcurrentAccessTests.cs
- test/BlittableTests/BlittableJsonWriterTests/FunctionalityTests.cs
- test/BlittableTests/BlittableJsonWriterTests/UnmanageJsonReaderTests.cs
- test/BlittableTests/BlittableJsonWriterTests/VariousPropertyAmountsTests.cs
- test/BlittableTests/MutatingJsonTests.cs
- test/BlittableTests/ObjectJsonParsingTests.cs
- test/Raven.Server.Tests/Documents/DocumentsCrud.cs
- test/Tryouts/Program.cs
Added Support for blittable reading from websocket
> Added Async-Await to blittable reading

- Raven.Tests/Bugs/WhereUsingUnicodeTheTextEnteredShouldNotBeNormalized.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4303
> RavenDB-4303 (unicode text not saved correctly)

- Raven.Abstractions/Util/RavenQuery.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4310
> RavenDB-4310 (failing tests 3.5)

- Raven.Abstractions/Util/RavenQuery.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4310
> RavenDB-4310

- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4318
http://issues.hibernatingrhinos.com/issue/RavenDB-4138
> RavenDB-4318 (Fixing Replication task + Purge relevant tombstones)

- Raven.Tests/Smuggler/SmugglerExecutionTests.cs
Fixing smuggler test that has different dump size on different machines
> RavenDB-4349

- src/Raven.Server/Routing/StringSegment.cs
- src/Raven.Server/Utils/IncludeUtil.cs
- test/FastTests/Utils/IncludeUtilTests.cs
* refactoring code for efficiency
* adding handling for array-of-array
> changes & refactorings for include path parsing

- Raven.Abstractions/Replication/ReplicationStatistics.cs
- Raven.Database/Bundles/Replication/Responders/ReplicationLastEtagResponder.cs
- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Database/Prefetching/PrefetchingBehavior.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4361
> RavenDB-4361 - Port RavenDB-4154 to 2.5

- src/Sparrow/Binary/Bits.cs
- src/Sparrow/Binary/PtrBitVector.cs
- src/Voron/Data/Compact/PrefixTree.NodesTable.cs
- src/Voron/Data/Compact/PrefixTree.cs
- src/Voron/Data/Compact/PrefixTreePage.cs
- src/Voron/Data/Compact/PrefixTreeTranslationTableHeader.cs
- src/Voron/Impl/Transaction.cs
- test/FastTests/Voron/Compact/SimplePrefixTree.cs
It passes even randomized structural testing.
> Full implementation of inserts for Prefix Trees

- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Database/Prefetching/PrefetchingBehavior.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4361
> RavenDB-4361 Port RavenDB-4154 to 2.5

- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Database/Prefetching/PrefetchingBehavior.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4361
> RavenDB-4361 - port from 2.5

- Raven.Database/Bundles/Replication/Controllers/ReplicationController.cs
- Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
- Raven.Database/DocumentDatabase.cs
- Raven.Database/Server/RavenDBOptions.cs
- Raven.Database/Server/Tenancy/DatabaseLandlord.cs
If a nodes leaves the cluster prevent replication outside its topology
> RavenDB-4306

- src/Raven.Server/Documents/Handlers/ChangesHandler.cs
- src/Raven.Server/Documents/NotificationsClientConnection.cs
- test/FastTests/Server/Documents/Notifications/ChangesTests.cs
- test/FastTests/Server/Documents/Notifications/ObservableExtensions.cs
By sending an error to the client and close the connection
> Handle errors in changes handler

- Raven.Database/Indexing/IndexingExecuter.cs
- Raven.Database/Storage/Esent/StorageActions/Tasks.cs
- Raven.Database/Storage/ITasksStorageActions.cs
- Raven.Database/Storage/Voron/StorageActions/TasksStorageActions.cs
- Raven.Tests.Issues/RavenDB-4222.cs
- Raven.Tests/Storage/TasksStorageActionsTests.cs
Delete tasks only before commit
> Tasks issue

- Raven.Voron/Voron/Impl/Transaction.cs
Modification that allows us to track properly and individually the behavior of pages.
> Page Tracking

- Raven.Abstractions/Data/Etag.cs
- Raven.Database/Actions/IndexActions.cs
- Raven.Smuggler/SmugglerDatabaseBetweenOperation.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-4379.cs
Make sure that documents added during smuggler "between" transfer will be smuggled as well
> fix for RavenDB-4379

- Raven.Database/Bundles/Replication/Controllers/ReplicationController.cs
- Raven.Tests.Bundles/Raven.Tests.Bundles.csproj
- Raven.Tests.Bundles/Replication/ConflictResolving.cs
- Raven.Tests.Common/ReplicationBase.cs
Merged with Marcin and added tests + some more data about progress in the task
> Raven db 3990

- Raven.Smuggler/SmugglerDatabaseBetweenOperation.cs
- Raven.Tests.Issues/RavenDB-4379.cs
- Raven.Tests/Smuggler/SmugglerBetweenTests.cs
fixed failing test that exposed issue with the fix -> in case of incremental smuggler "between" operation, it should not skip changes
> another fix related to RavenDB-4379

- src/Voron/Data/RawData/ActiveRawDataSmallSection.cs
- src/Voron/Impl/LowLevelTransaction.cs
- src/Voron/Impl/Scratch/ScratchBufferFile.cs
- src/Voron/Platform/Win32/Win32MemoryMapPager.cs
- test/Tryouts/Program.cs
* fix for Voron bug -> allocation that is too large, causes bad pointers
* minor refactorings
> fix of Voron issue, some minor refactorings

- src/Raven.Client/Connection/Async/AsyncServerClient.cs
- src/Raven.Client/Connection/Async/AsyncServerClientBase.cs
- src/Raven.Client/ConventionBase.cs
- src/Raven.Client/Counters/CountersConvention.cs
- src/Raven.Client/Counters/Replication/CounterReplicationInformer.cs
- src/Raven.Client/FileSystem/FilesConvention.cs
- src/Raven.Client/TimeSeries/Replication/TimeSeriesReplicationInformer.cs
- src/Raven.Client/TimeSeries/TimeSeriesConvention.cs
**Breaking change**
As discussed in https://github.com/ravendb/ravendb/pull/627
> AllowMultipuleAsyncOperations -> AllowMultipleAsyncOperations

- Raven.Client.Lightweight/Changes/RemoteChangesClientBase.cs
- Raven.Client.Lightweight/Connection/IReplicationInformerBase.cs
- Raven.Client.Lightweight/Connection/ReplicationInformerBase.cs
- Raven.Tests.Core/ChangesApi/ImplementingChangesClient.cs
+ some better logging for the reason we fail to establish a connection
> RavenDB-944 when server is down continue to try and reconnect with it

- test/FastTests/Server/Basic/RavenTestBase.cs
* Changed PathsToDelete to be static because we would not delete the paths if server is not disposed
* Changed ref count to be long with interlock operations so not to take the lock when we don't need to
> RavenDB-4417

- src/Sparrow/Json/LazyDoubleValue.cs
- src/Sparrow/Json/Parsing/UnmanagedJsonParser.cs
- test/FastTests/Properties/launchSettings.json
- test/FastTests/Voron/Tables/Bugs.cs
- test/FastTests/Voron/Tables/TableStorageTest.cs
Repeated Insertion in the same transaction will eventually fail on Tables [Repro]
> RavenDB-4464: Failing Test

- Raven.Tests.Issues/RavenDB_4487.cs
Ehh, I've made cherry-pick in last on my changes from v3.0.
> fixed v3.5 build

- Raven.Database/Indexing/IndexingExecuter.cs
handle properly OperationCanceledException which is expected in the context
> RavenDB-4515 fix -> better exception handling in indexing executer 

- Raven.Client.Lightweight/Connection/ObservableLineStream.cs
- Raven.Tryouts/Program.cs
make sure that http connection is returned to HttpClientCache when changes API faults
> fix for RavenDB-4545 (3.0)

- src/Sparrow/Sparrow.xproj
- src/Voron/Data/BTrees/RecentlyFoundTreePages.cs
- src/Voron/Data/BTrees/Tree.cs
- src/Voron/Impl/Backup/MinimalIncrementalBackup.cs
- src/Voron/Impl/Constants.cs
- src/Voron/Impl/Journal/JournalReader.cs
- src/Voron/Impl/Journal/TransactionHeader.cs
- src/Voron/Impl/Journal/WriteAheadJournal.cs
- src/Voron/Impl/LowLevelTransaction.cs
- src/Voron/Impl/Paging/AbstractPager.cs
- src/Voron/Platform/Win32/Win32JournalWriter.cs
- src/Voron/StorageEnvironmentOptions.cs
- src/Voron/Voron.xproj
- test/FastTests/FastTests.xproj
- test/FastTests/Server/Documents/SqlReplication/CanReplicate.cs
- test/FastTests/Voron/Bugs/RavenDB_2850.cs
- test/FastTests/Voron/ScratchBuffer/ScratchCanForceToFlushOldPages.cs
- test/FastTests/Voron/Storage/InitialSize.cs
- test/FastTests/Voron/Trees/TreeStateTests.cs
- test/FastTests/Voron/ValidHeaders.cs
Voron now supports page sizes of 4Kb, 8Kb, 16Kb and 32Kb.
> RavenDB-4482

- Rachis/Rachis/Storage/PersistentState.cs
- Raven.Database/Counters/CounterStorage.cs
- Raven.Voron/Voron/Impl/Paging/AbstractPager.cs
- Raven.Voron/Voron/Impl/Paging/IVirtualPager.cs
- Raven.Voron/Voron/Platform/Win32/Win32MemoryMapPager.cs
- Raven.Voron/Voron/Trees/Page.cs
- Raven.Voron/Voron/Trees/Tree.cs
- Raven.Voron/Voron/Trees/TreeIterator.cs
> IO improvements

- Raven.Database/Bundles/Expiration/ExpiredDocumentsCleaner.cs
- Raven.Database/Server/Controllers/DocumentsBatchController.cs
- Raven.Database/Server/Controllers/DocumentsController.cs
- Raven.Studio.Html5/App/commands/evalByQueryCommand.ts
- Raven.Studio.Html5/App/views/deleteDocumentsMatchingQueryConfirm.html
http://issues.hibernatingrhinos.com/issue/RavenDB-4564
> RavenDB-4564 Expiration bundle task continues to run after database was shutdown

- Raven.Client.Lightweight/Document/RemoteBulkInsertOperation.cs
- Raven.Tests.Issues/Raven.Tests.Issues.csproj
- Raven.Tests.Issues/RavenDB-4563.cs
http://issues.hibernatingrhinos.com/issue/RavenDB-4563
> RavenDB-4563 BulkInsert hangs when server is down
