Raven.Database/Indexing/Index.cs, Raven.Database/Indexing/IndexStorage.cs, Raven.Database/Storage/BaseBackupOperation.cs
* notice that there is still an issue on Voron incremental backup.
If the first backup had a bad index on Voron and the second one succeeds restoring the database will throw an exception.
* you might actually need to try and access the restored database to cause the exception.
I can't reproduce this on my master because the backup will fail entirely before the latest changes.   
i'll open an issue on this and include my branch path to reproduce
=> added notification when index backup fails

Raven.Database/Bundles/Replication/Controllers/ReplicationController.cs, Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
+ limiting max number of results in attachments in ReplicationTask
=> added constraint to low-memory calculation during last etag retrieval

Raven.Client.Lightweight/FileSystem/AbstractFilesQuery.cs
The string.format parameters had beend counted one-based. Nothing failed but the log message could not be created.
Tested it successfully in a running client application but apperently there is no unittest.
=> fixed string.format parameters in log message

Raven.Database/Actions/LastCollectionEtags.cs
if indexes are stale, there is no way to indicate which etag from particular collection was last without breaking the IsStale mechanism in queries
=> fixed LastCollectionEtags initialization

Raven.Database/Bundles/SqlReplication/SqlReplicationTask.cs
When you reset a Sql replication the last document in all the other replication would get replicated again
=> Fixing an issue where SqlReplicaion would replicate the last Etag document

Raven.Database/Bundles/SqlReplication/SqlReplicationTask.cs
When you run sql replication task the last etag document is always been replicated although it was already replicated.
=> fixing an issue where Sql replication would replicate last Etag document

Raven.Voron/Voron/Util/MemoryUtils.cs
Code that forces the JIT to use 3 registers less improving the performance in the 16/32 bytes range. I doubt very much we can do better than this.
=> Last change to memcpy and memcmp

Raven.Database/Json/ScriptedJsonPatcher.cs, Raven.Tests/Patching/AdvancedPatching.cs
I'm leaving the field with null value, allowing one time to execute so
this.Test = this;
is working
=> preventing recursion in JS patches

Raven.Database/Indexing/QueryBuilder.cs, Raven.Tests.Issues/Raven.Tests.Issues.csproj, Raven.Tests.Issues/RavenDB-3225.cs
(actual problem occurs when the in method is in the start and the rest of the query is at the left of it)
=> Adding fail test for multiple term query with date time inside

Raven.Database/Actions/DocumentActions.cs
We make sure of not deserializing the batch inside the database write lock. It has the interesting side effect of improving bulk insert performance by 25%
Before the commit:
Bulk inserted received 50.000 documents in 00:00:30.9422179, task #: 1
After the commit:
Bulk inserted received 50.000 documents in 00:00:24.0021129, task #: 1
=> Review this commit... There is nothing sooo strange here but the improvement is too good to be true.

Raven.Database/Config/InMemoryRavenConfiguration.cs, Raven.Database/Extensions/IOExtensions.cs, Raven.Database/Linq/QueryParsingUtils.cs, Raven.Tests.Core/Configuration/ConfigurationTests.cs
_All_ databases from _all_ servers will point to the same directory e.g.
C:\Users\USER_NAME\AppData\Local\Temp\Raven\CompiledIndexCache
Relative paths are still supported but TempDir is a base directory for them, absolute paths works also.
=> moved CompiledIndexCacheDirectory to TEMP

Raven.Client.Lightweight/Linq/DynamicAggregationQuery.cs, Raven.Tests.Issues/Raven.Tests.Issues.csproj, Raven.Tests.Issues/RavenDB-3136.cs
after the renaming the key HandleRenames was adding to facetResults the same value under the key before the rename to (Key_Range)
now we keep the previous key before the change and remove the renamed key so we wont have multiple values.
In case of using aggregate with string the renaming isn't required and therefor it works fine.
=> RavenDB-3136 Query AggregateByInteger and Count fails

Raven.Abstractions/Exceptions/ImplicitFetchFieldsFromDocumentNotAllowedException.cs, Raven.Abstractions/Raven.Abstractions.csproj, Raven.Database/Actions/DocumentActions.cs, Raven.Database/Actions/QueryActions.cs, Raven.Database/Config/InMemoryRavenConfiguration.cs, Raven.Database/Config/StronglyTypedRavenSettings.cs, Raven.Database/Impl/DocumentRetriever.cs, Raven.Database/Indexing/IndexingExecuter.cs, Raven.Database/Queries/MoreLikeThisQueryRunner.cs, Raven.Database/Server/WebApi/Filters/RavenExceptionFilterAttribute.cs, Raven.Tests.Core/Configuration/ConfigurationTests.cs
I created the setting discussed in [this](Raven/ImplicitFetchFieldsFromDocumentMode) google groups thread.
The setting is named *Raven/ImplicitFetchFieldsFromDocumentMode* and configures how RavenDB will handle requested fields that should be fetched, if they are not stored in the index.
Possible values are:
- *Enabled* This is the default value. Fields are fetched from the document. (Exactly how RavenDB works until now)
- *DoNothing* No fields are fetched from the document.
- *Exception* An exception is thrown with a detailed error message.
=> Setting how fields are fetched from the document in projections

Raven.Voron/Voron/Slice.cs, Raven.Voron/Voron/Util/MemoryUtils.cs
Current implementation allows inlining therefore giving 3.7x gains on Slice key comparison operations.
While all tests pass, because the type of change it could use an independent review.
=> Fully managed and massive improvement to the memory compare implementation.

Raven.Client.Lightweight/Connection/Implementation/HttpJsonRequestFactory.cs, Raven.Client.Lightweight/Document/DocumentStore.cs, Raven.Client.Lightweight/DocumentStoreBase.cs, Raven.Client.Lightweight/IDocumentStore.cs, Raven.Database/Client/EmbeddableDocumentStore.cs, Raven.Database/Client/EmbeddedDocumentStore.cs, Raven.Tests.Issues/Raven.Tests.Issues.csproj, Raven.Tests.Issues/RavenDB-3301.cs
Creating HttpJsonRequestFactory only once per store.
When changing the cache size, only the cache size is being changed
=> RavenDB-3301 Any changes to JsonRequestFactory before calling Initialize() should be maintained after it.

Raven.Abstractions/Indexing/IndexDefinition.cs, Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs, Raven.Client.Lightweight/Connection/IDatabaseCommands.cs, Raven.Client.Lightweight/Connection/ServerClient.cs, Raven.Client.Lightweight/Indexes/AbstractIndexCreationTask.cs, Raven.Client.Lightweight/Indexes/IndexDefinitionBuilder.cs, Raven.Database/DocumentDatabase.cs, Raven.Database/Indexing/GenerateIndexDefinitionCode.cs, Raven.Database/Server/Controllers/IndexController.cs, Raven.Tests.Issues/Raven.Tests.Issues.csproj, Raven.Tests.Issues/RavenDB-3314.cs
Client can set index priority through client API and also through index definition
=> RavenDB-3314 Allow to set index priority through the API

Raven.Abstractions/Data/Constants.cs, Raven.Database/Actions/IndexActions.cs, Raven.Database/Actions/NotificationActions.cs, Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs, Raven.Database/Bundles/Replication/Triggers/VirtualDeleteTrigger.cs, Raven.Database/Server/Controllers/IndexController.cs, Raven.Tests.Core/Replication/IndexReplication.cs
* on index deletion, index tombstone is written
* in replication task, if index tombstones are discovered, index DELETE requests are issued
* if replicated to all destinations, tombstone is purged
=> fix for RavenDB-3304 -> clean branch

Raven.Smuggler/SmugglerDatabaseBetweenOperation.cs, Raven.Tests.Issues/Raven.Tests.Issues.csproj, Raven.Tests.Issues/RavenDB-3152.cs
fixed filtering when moving data between two databases.
last etag is being updated for each document
fixed for streaming and also for the case when streaming isn't supported
Signed-off-by: Hila Mefano <hila@ayende.com>
=> RavenDB-3152 Smuggler client side filtering should not impact how we get the next etag

Raven.Abstractions/Exceptions/InvalidSpatialShapeException.cs, Raven.Abstractions/Raven.Abstractions.csproj
No need to take a dependency on Spatial4n.Core.NTS in Raven.Abstractions.
=> removed unnecessary dependency

Raven.Client.Lightweight/Indexes/AbstractIndexCreationTask.cs, Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
I think it should be done this way, please verify
=> GetLegacyIndexDefinition should change back PrettifyGeneratedLinqExpressions to the original value

Bundles/Raven.Bundles.Authorization/Raven.Bundles.Authorization.csproj, Bundles/Raven.Bundles.CascadeDelete/Raven.Bundles.CascadeDelete.csproj, Bundles/Raven.Bundles.Encryption.IndexFileCodec/Raven.Bundles.Encryption.IndexFileCodec.csproj, Raven.Abstractions/Raven.Abstractions.csproj, Raven.Backup/Raven.Backup.csproj, Raven.Client.Lightweight/Raven.Client.Lightweight.csproj, Raven.Database/Raven.Database.csproj, Raven.Migration/Raven.Migration.csproj, Raven.Smuggler/Raven.Smuggler.csproj, Raven.StorageExporter/Raven.StorageExporter.csproj
Fixed: Build of smuggler fails because x86 doesnt exist anymore and it is still the default.
=> RavenDB-3497

Raven.Abstractions/Replication/ReplicationDestination.cs, Raven.Tests.Bundles/Replication/CollectionSpecific.cs
minor change - bringing back IgnoredClient = true on SourceCollection's set
=> minor fix for replication from specific collections

Raven.Database/Server/Controllers/QueriesController.cs, Raven.Database/Server/Controllers/RavenBaseApiController.cs, Raven.Database/Server/Controllers/RavenDbApiController.cs
Fixing : 
http://issues.hibernatingrhinos.com/issue/RavenDB-3713
The issue was that double escaping would remove '+' from the Lucene query string
resulting in the wrong query been processed.
=> Double escape only for older client version (under 3.0)

Raven.Database/Indexing/BaseBatchSizeAutoTuner.cs, Raven.Database/Indexing/MapReduceIndex.cs, Raven.Database/Indexing/ReducingExecuter.cs, Raven.Database/Storage/Esent/StorageActions/MappedResults.cs, Raven.Database/Storage/IMappedResultsStorageAction.cs, Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs, Raven.Tests.Issues/RavenDB_766.cs, Raven.Tests.Issues/RavenDB_863.cs, Raven.Tests/Storage/Voron/MappedResultsStorageActionsTests.cs, Raven.Voron/Voron/Trees/TreeMutableState.cs
This is the best I could do without seriously rethinking how map-reduce works. I must say that the constraints of the data model does not help the case. RavenDB-3724 is a must to be done for RavenDB rethinking the storage model. 
Another thing that will improve this is changing the storage to a binary representation as Json Serialization/Deserialization is insanely costly in this scenario.
After I finish the prefix trees POC I will look into what we can do for multi-step map-reduce and if they could not be for 4.0 at least know what we need in order to not closing the door to it when we rethink the indexing storage model (which is a must for 4.0).
=> Some optimizations RavenDB-3724

Raven.SlowTests/Security/OAuth/ReplicationWithOAuthMultipleKeys.cs, Raven.Tests.Common/ReplicationBase.cs
Sometimes GetIndex would be called before it was replicated.
=> Fixing a race condition in replication of indexes

Raven.Database/Config/MemoryStatistics.cs, Raven.Database/Indexing/AbstractIndexingExecuter.cs, Raven.Database/Indexing/IndexStorage.cs, Raven.Database/Indexing/ReducingExecuter.cs, Raven.Database/Storage/Esent/StorageActions/MappedResults.cs, Raven.Database/Storage/IMappedResultsStorageAction.cs, Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs, Raven.Tests/Storage/Voron/MappedResultsStorageActionsTests.cs, Raven.Voron/Voron/Impl/WriteBatch.cs, Raven.Voron/Voron/Trees/Cursor.cs, Raven.Voron/Voron/Trees/Tree.cs, Raven.Voron/Voron/Trees/TreeIterator.cs
I tried several approaches to diminish allocations on Map-Reduce and other places. Some worked, some didnt and ended up reverting some of them. I tried to keep the tradeoff leaning toward performance, lost a couple of seconds in my test environment, but allocations diminish a lot in the process so it should be less taxing when we are memory starved. 
I still have a couple of ideas to bounce over the code, but I didnt want to deviate too much from the current unstable. Took me a bit to rebase everything at this point.
=> Mostly avoiding allocations without changing the performance-memory tradeoff.

Raven.Tests.FileSystem/CommandsUsage.cs
"fs/{fileSystemName}/config"  is now called on FS init
The assertion in the test didn't count that as a request.
=> RavenDB-3796 - fix of Can_get_stats_for_all_active_file_systems

Raven.Tests.Core/BulkInsert/ChunkedBulkInsert.cs
Fixed ValidateChunkedBulkInsertOperationsIDsCount 
Can't reproduce failure on ShouldSupportIncremental (350 pass iterations)
=> Raven db 3796

Raven.Database/Config/InMemoryRavenConfiguration.cs
make assembly catalog static so it is evaluated once per process
=> RavenDB-3854 fix

Raven.Abstractions/Data/Constants.cs, Raven.Abstractions/Smuggler/SmugglerDatabaseApiBase.cs, Raven.Abstractions/Smuggler/SmugglerDatabaseOptions.cs, Raven.Database/Server/Controllers/BulkInsertController.cs, Raven.Tests/Smuggler/SmugglerExecutionTests.cs
make sure Smuggler sends heartbeat documents if skipping lots of documents due to continuation token for large dump files
=> fix for RavenDB-3868

Raven.Database/Server/Security/MixedModeRequestAuthorizer.cs, Raven.Tests/Smuggler/SmugglerExecutionTests.cs
Problem when resource name is null and resource prefix is string empty.
Also there is a race condition in the wait for periodic export
=> Fix for SmugglerCanUnderstandPeriodicBackupFormat

Raven.Abstractions/Json/Linq/RavenJValue.cs, Raven.Tests.MailingList/Raven.Tests.MailingList.csproj, Raven.Tests.MailingList/ValerioBorioni.cs
this causes the IDocumentSession to detect frequently used reference documents as changed, making a lot of unnecessary optimistic concurrency and index invalidations.
I think this happens because RavenJValue parsed from entity instance knows the property type, while it has no clue when it comes from server.
=> RavenJValue recognize NaN float is equal to NaN string

Raven.Database/Actions/MaintenanceActions.cs, Raven.Tests.Issues/RavenDB_3109.cs
The problem was a NRE in the initialize of the document database.
Also the number of alerts changed.
=> Fixing RavenDB_3109

Raven.Database/Server/Controllers/SubscriptionsController.cs
Subscriptions are not using a BufferedStream which is a requirement to ensure high performance operation of Network Streams.
=> RavenDB-3946: Slow Subscriptions.

Raven.Abstractions/Connection/CompressedContent.cs, Raven.Abstractions/Connection/JsonContent.cs, Raven.Abstractions/Connection/WebResponseExtensions.cs, Raven.Abstractions/Raven.Abstractions.csproj, Raven.Abstractions/Util/Streams/BufferPoolMemoryStream.cs, Raven.Abstractions/Util/Streams/BufferSharedPools.cs, Raven.Abstractions/Util/UndisposableStream.cs, Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs, Raven.Client.Lightweight/Connection/CompressedStreamContent.cs, Raven.Client.Lightweight/Connection/Implementation/HttpJsonRequest.cs, Raven.Database/FileSystem/Storage/Voron/StorageActionsAccessor.cs, Raven.Database/Raven.Database.csproj, Raven.Database/Server/AppBuilderExtensions.cs, Raven.Database/Server/Controllers/MultiGetController.cs, Raven.Database/Server/Controllers/RavenBaseApiController.cs, Raven.Database/Server/WebApi/Handlers/GZipToJsonAndCompressHandler.cs, Raven.Database/Storage/Voron/StorageActions/DocumentsStorageActions.cs, Raven.Database/Storage/Voron/StorageActions/MappedResultsStorageActions.cs
I was able to diminish the amount of network trasference by more than 50% on bulk inserts and multiple entities loads. We were not compressing the data from client to server. 
Most of my tests were oriented toward batching and bulk processing where TCP latency influence should be minimal. TCP streams are more compact now, but because of the nature of the test set I havent seen any measurable effect.
Analysis of wireshark dumps suggest that we are already in the ballpark of what is achievable without a serious rework of the network streams infrastructure and use (something we should do when thinking of supporting HTTP/2 for v4.0).
=> RavenDB-3947

Bundles/Raven.Client.UniqueConstraints/UniqueConstraintExtensions.cs, Raven.Client.Lightweight/Document/InMemoryDocumentSessionOperations.cs, Raven.Tests.Bundles/Raven.Tests.Bundles.csproj, Raven.Tests.Bundles/UniqueConstraints/Bugs/ValerioBorioni.cs
I don't like the solution very much due to the cast in the bundle : 
var inMemory = ((InMemoryDocumentSessionOperations)session);
Is there a better way to do that ?
=> Load by unique constraint always hit server

Raven.Sparrow/Sparrow.Tests/Hashing.cs
issue introduced after crlf + tabs to spaces normalization
=> RavenDB-3983 Failing test: Sparrow.Tests.HashingTests.XXHash32

Raven.Database/Bundles/SqlReplication/SqlReplicationTask.cs, Raven.Database/Indexing/IndexingExecuter.cs, Raven.Database/Prefetching/PrefetchingBehavior.cs, Raven.Studio.Html5/App/views/indexes.html
and RavenDB-4009 When early exist is used in loading docs from disk, emit a log warning
=> Prefetching improvements

Raven.Tests.Core/Configuration/ConfigurationTests.cs
Adding missing configuration, BatchTimeout, from configuration test
=> RavenDB-4108:

Raven.Database/Bundles/Replication/Tasks/ReplicationTask.cs
Added logging when failing to remove replication tasks
=> RavenDB-4146 (ReplicationTask does a busy-wait loop)

Raven.Abstractions/Replication/ReplicationDocument.cs, Raven.Client.Lightweight/Connection/Request/ClusterAwareRequestExecuter.cs, Raven.Database/Bundles/Replication/Controllers/ReplicationController.cs
Fixing an issue where we would take the latest topology from the first node that claims to be the leader while there could be multiple such nodes.
Now we pick the one with the highest Term first only then we look at the commit index.
=> RavenDB-4125 (Failing raft tests)

Raven.Studio.Html5/App/models/collection.ts, Raven.Studio.Html5/App/views/documents.html
pursuant to raven db google groups post: https://groups.google.com/forum/#!topic/ravendb/XlfVUSMsLOI
Cosmetic: documents view will run a filter on collection labels, replacing double underscore **(__)** with a forward slash **(/)**. This will give a way to group collections while preserving C# viable `Raven-Entity-Name`.
I did this out of my own OCD - having all of the collections just verbatim dumped into the list drives me crazy. I, and many programmers I know, work better when we've got some control over the way things are sorted and arranged.
It's a small change, and the ideal situation would just be a metadata **Raven-Entity-Label** that can keep it separate from the actual Entity Name. I am simply out of my depth for adding a new metadata into Raven. I was also advised to avoid that …
=> cosmetic: document labels replace '__' with '/'.

Raven.Database/Indexing/IndexMerging/IndexMerger.cs, Raven.Tests.Issues/Raven.Tests.Issues.csproj, Raven.Tests.Issues/RavenDB_4099.cs
=> [4.0] RavenDB-4099 index merger should not compare variable names in expression

Raven.Database/Prefetching/PrefetchingBehavior.cs, Raven.Database/Storage/Esent/StorageActions/Indexing.cs, Raven.Database/Storage/Voron/StorageActions/IndexingStorageActions.cs, Raven.Tests.Issues/Raven.Tests.Issues.csproj, Raven.Tests.Issues/RavenDB_4215.cs
This will prevent an infinite loop when executing a RemoveFromIndex task.
=> RavenDB-4215 IndexDoesNotExistsException: There is no reduce index named

RavenDB-Dnx.sln, src/Voron/Data/BTrees/Tree.MultiTree.cs, src/Voron/Data/BTrees/TreeFlags.cs, src/Voron/Data/BTrees/TreePage.cs, src/Voron/Data/BTrees/TreePageSplitter.cs, src/Voron/Data/BTrees/TreeRebalancer.cs, src/Voron/Data/BTrees/TreeRootHeader.cs, src/Voron/Data/BTrees/TreeSizeOf.cs, src/Voron/Data/Fixed/FixedSizeTreeHeader.cs, src/Voron/Data/Fixed/FixedSizeTreePage.cs, src/Voron/Data/RootHeader.cs, src/Voron/Data/RootObjectType.cs, src/Voron/Debugging/DebugStuff.cs, src/Voron/Debugging/StorageReport.cs, src/Voron/Debugging/StorageReportGenerator.cs, src/Voron/Impl/Compaction/StorageCompaction.cs, src/Voron/Impl/FileHeaders/FileHeader.cs, src/Voron/Impl/FileHeaders/HeaderAccessor.cs, src/Voron/Impl/Journal/TransactionHeader.cs, src/Voron/Impl/Scratch/ScratchBufferPool.cs, src/Voron/Impl/Transaction.cs, src/Voron/StorageEnvironment.cs, test/Sparrow.Tests/BitVectors.cs, test/Sparrow.Tests/Properties/launchSettings.json, test/Voron.Tests/Bugs/UpdateLastItem.cs, test/Voron.Tests/Properties/launchSettings.json, test/Voron.Tests/ValidHeaders.cs
Now there is an explicit shared RootObject header we can use instead of casting to a TreeRootObject to know the type of the object. Also moved the shared object from an internal implementation detail to the Voron.Data namespace.
=> RavenDB-4132: Root Objects headers should be more uniform.

Raven.Studio.Html5/App/models/documentMetadata.ts, Raven.Studio.Html5/App/views/editDocument.html
Updated the "Edit Document" page to understand the "prettified labels" display added in my last set of pull requests.
Display is understood in both the upper pane, and the right pane.
=> cosmetic: added new pretty label display to edit document page

Raven.Studio.Html5/App/models/documentMetadata.ts
This pull fixes an issue where creating a new document throws an error due to the label regex.
http://issues.hibernatingrhinos.com/issue/RavenDB-4228
=> Fixed issue with creating new documents.

Raven.Database/DiskIO/DiskPerformanceTester.cs, Raven.Database/Prefetching/PrefetchingBehavior.cs
not properly disposing of CancellationTokenSources after linking them
http://issues.hibernatingrhinos.com/issue/RavenDB-4231
=> RavenDB-4231

Raven.Client.Lightweight/Indexes/ExpressionStringBuilder.cs
- because of byte enum
- because of empty array
Porting from 3.0
=> RavenDB-4276 Index deploy errors

Bundles/Raven.Client.UniqueConstraints/UniqueConstraintExtensions.cs, Raven.Client.Lightweight/IAdvancedDocumentSessionOperations.cs, Raven.Tests.Bundles/Raven.Tests.Bundles.csproj, Raven.Tests.Bundles/UniqueConstraints/Bugs/MyCustomDocumentSession.cs, Raven.Tests.Bundles/UniqueConstraints/Bugs/ValerioBorioni.cs
I'm experimenting with wrapping IDocumentSession, and a couple of casts in Client.UniqueConstraints broke
=> Unique constraint work with i document session encapsulation

Raven.Tests/Smuggler/SmugglerExecutionTests.cs
Test fail because increase of the dump file size
=> RavenDB-4349

Raven.Database/Actions/IndexActions.cs, Raven.Database/Config/InMemoryRavenConfiguration.cs, Raven.Database/Config/StronglyTypedRavenSettings.cs
numeric flag to control amount of documents loaded in initial precomputed batch for new index
=> flag to control initial precomputed batch size

Bundles/Raven.Client.Authorization/AuthorizationClientAsyncExtensions.cs, Bundles/Raven.Client.Authorization/Raven.Client.Authorization.csproj
Includes in the Raven.Client.Authorization extensions for IAsyncDocumentSession. I basically copied the code from the AuthorizationClientExtensions and switched the implementations to the Async equivalents when applicable.
=> included AuthorizationClientAsyncExtensions

Raven.Database/Prefetching/PrefetchingBehavior.cs
no need to remove the outdated documents by etag after a replication batch is complete,
since we already filtered them when fetching from the queue
=> RavenDB-4361 - Port a change from 2.5

Raven.Abstractions/Data/Constants.cs, Raven.Abstractions/Exceptions/TotalDataSizeExceededException.cs, Raven.Abstractions/Raven.Abstractions.csproj, Raven.Client.Lightweight/Connection/Async/AsyncServerClient.cs, Raven.Client.Lightweight/Connection/IDatabaseCommands.cs, Raven.Client.Lightweight/Connection/ServerClient.cs, Raven.Database/Actions/IndexActions.cs, Raven.Database/Actions/QueryActions.cs, Raven.Database/Config/InMemoryRavenConfiguration.cs, Raven.Database/Config/StronglyTypedRavenSettings.cs, Raven.Database/Server/Controllers/IndexController.cs, Raven.Tests.Core/Configuration/ConfigurationTests.cs, Raven.Tests.Issues/NewIndexOptimizationIssue.cs, Raven.Tests.Issues/Raven.Tests.Issues.csproj
* limit new index precompute operation to maximum size, if total accumulated document size exceeds the default, the operation is aborted
* relevant test
=> limit new index precompute operation to maximum total size

Raven.Client.Lightweight/Document/Async/AsyncDocumentSession.cs, Raven.Client.Lightweight/Document/InMemoryDocumentSessionOperations.cs
Make sure that during streaming missing properties won't be registered and saved (RavenDB-4387)
-> makes no sense to save the missing properties during streaming, since we can potentially go over ALOT of documents that are unlikely to be saved later
That should lessen memory usage during streaming
(https://groups.google.com/forum/#!topic/ravendb/TWxDlYkObP0)
=> Fix for RavenDB-4387

Raven.Database/Prefetching/PrefetchingBehavior.cs
Fixing an issue where AddFutureBatch would hang in an infinite call stack (since it re-call itself on different threads)
=> RavenDB-4414

Raven.Client.Lightweight/Connection/ObservableLineStream.cs
make sure that http connection is returned to HttpClientCache when changes API faults
=> fix for RavenDb-4545 (3.5)

src/Voron/Data/BTrees/TreePage.cs
Microarchitecture level optimization to avoid making useless pointer calculations that cause load-store pipeline stalls on the loop. (Insanely low level optimization... I will look in the future into making those less DRAM bound as they are right now)
=> CPU optimization

src/Voron/Impl/Journal/JournalReader.cs, src/Voron/Impl/Journal/WriteAheadJournal.cs, test/FastTests/Voron/Journal/EdgeCases.cs, test/SlowTests/SlowTests.xproj, test/SlowTests/Voron/RecoveryMultipleJournals.cs
No difference in OPs per second for my very limited tests on v4.0 (do not have the correct infrastructure to do proper testing of such cases yet); but the saving is significant. 
100000 transactions of 10 insert operations each. 
With single page header: 20 journals
Without single page header: 25 journals
Saving: 5 journals = 64Mb * 5 = 320MB of IO
=> RavenDB-4484

src/Sparrow/Memory.cs, src/Sparrow/project.json, src/Voron/Slice.cs
Even though the use of the inline version is discouraged in cases where there is a likely situation that the memory chunk comparison have to handle bigger than 128 bytes memory chunks.
=> RavenDB-4567
